### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by matti044** [morrolinux/simple-ehm#12]
non riesco a runnarlo, uso Mac
nel terminale scrivo 

`/Users/mattiasantini/Documents/simple-ehm-main/simple_ehm-runnable.py /Users/mattiasantini/Documents/prova/IMG_2371.MOV`

ma viene questo errore:

`Traceback (most recent call last):
  File "/Users/mattiasantini/Documents/simple-ehm-main/simple_ehm-runnable.py", line 10, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'`

Sono nuovo e quindi non so cosa fare, Matplotlib dovrei averlo installato.
Cosa sbaglio?
Grazie mille

**Comment by niccolopetti** [comment]
`pip3 install matplotlib`
se non va prova 
`pip install matplotlib`
se dovessero mancare altri moduli dai un occhiata a #10
(rimarrebbe solo da installare ffmpeg)

**Comment by matti044** [comment]
Grazie mille, ma da comunque lo stesso errore.
invece inserendo quello che c'è scritto in #10 mi dice 
`zsh: permission denied: /Users/mattiasantini/Documents/simple-ehm-main/REQUIREMENTS.md`
non capisco molto bene cosa devo fare!
Ho cercato su internet e dice che Mac è come se usasse un python suo in cui non ci sono installati Matplotlib ecc. 
Se è la soluzione, c'è un modo per dire al terminale di usare python scaricato e non quello nativo?
Grazie

**Comment by morrolinux** [comment]
`REQUIREMENTS.md` è un altro file, diverso da `requirements.txt`
Inoltre `requirements.txt` non era presente perché non avevo ancora accettato la pull request. 
fai git pull (o clona nuovamente il repo) e riprova

**Comment by matti044** [comment]
Scusa, come ho detto sono nuovo, come si fa git pull?

**Comment by morrolinux** [comment]
Si scrive
git pull
E si preme invio

Il mar 19 gen 2021, 21:03 matti044 <notifications@github.com> ha scritto:

**Comment by matti044** [comment]
ah ok! l'ho fatto ma dice
`fatal: not a git repository (or any of the parent directories): .git`

**Comment by morrolinux** [comment]
Con il terminale devi essere nella cartella di simple-ehm

Il mar 19 gen 2021, 21:07 matti044 <notifications@github.com> ha scritto:

**Comment by matti044** [comment]
fatto ma prima ho dovuto fare git init

**Comment by matti044** [comment]
da sempre lo stesso errore anche facendo così

**Comment by matti044** [comment]
come se non avessi Matplotlib ma lo ho installato...

**Comment by matti044** [comment]
sono riuscito a togliere l'errore da mac ma per colpa dell'm1 mi viene 'illegal hardware instruction'
Allora ho provato da windows ma dice sempre così:
`extracting audio track...
Traceback (most recent call last):
  File ".\simple_ehm-runnable.py", line 285, in <module>
    wav_path = convert_input(video_path)
  File ".\simple_ehm-runnable.py", line 73, in timed
    output = f(*args, **kw)
  File ".\simple_ehm-runnable.py", line 85, in convert_input
    subprocess.Popen(cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE).wait()
  File "C:\Users\Mattia Santini\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Mattia Santini\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Impossibile trovare il file specificato`
Cosa sbaglio ora?

**Comment by matti044** [comment]
Risolto!!!!!
Ultima domanda dove si trovano i sottotitoli generati

**Comment by morrolinux** [comment]
Ok, dato che il problema originale è risolto chiudo la issue. La discussione su #7 può continuare nell'apposito thread
