### ISSUE TITLE
Stuck in the cutting - merging process

### ISSUE THREAD

**Issue by RCapolungo** [morrolinux/simple-ehm#4]
Hello,

i'm having a problem during the cutting - marging phase.
i'm using windows 10 as OS, ffmpeg 4.2.2 and python 3.8.6 .
i don't know if it's a ffmpeg or a program problem but it gets stuck after creating 2 of the 6 instances and only one working (it stop working after cutting 6 packages).

i'll leave here a photo of the console.

![Screenshot 2020-12-13 144130](https://user-images.githubusercontent.com/61745644/102014232-468b9780-3d55-11eb-9166-c0ebbb63e7a3.png)

**Comment by pokemaniac05** [comment]
May you send here RAM size, CPU type, and other useful information to reproduce this issue? Did you install all requirements from [requirements. md](https://github.com/morrolinux/simple-ehm/blob/main/REQUIREMENTS.md)? May you install the latest version of [ffmpeg](https://ffmpeg.org/download.html#build-windows) (4.3.1)?

**Comment by RCapolungo** [comment]
Sure.
16 GB RAM
AMD Ryzen 5 3600
Windows 10 build 18363

All requirements has been installed.
I also update ffmpeg to 4.3.1 and unfortunately the problem is still there.
ffmpeg is precompiled, while i got python from the installer on https://www.python.org/downloads/ so at the end it should be precompiled too.

**Comment by morrolinux** [comment]
What's your CPU and memory usage during "stuck" execution? For how long did you see it stuck before giving up? 
The `ffmpeg` process `stdout` and `stderr` is suppressed in https://github.com/morrolinux/simple-ehm/blob/11e90f9eb25f03209ef9db077da7bf708439666a/simple_ehm-runnable.py#L243 
You can remove `stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE` to let the shell print watever ffmpeg is outputting and maybe there's some useful clue to what's really happening and why the process is stuck

**Comment by RCapolungo** [comment]
I followed your suggestion and removed these arguments and it starts working fine until last frame :(
idk why but when arrives the last frame ffmpeg stops working.

This is a screenshot of the task manager.
![Screenshot 2020-12-14 143514](https://user-images.githubusercontent.com/61745644/102087682-325d9e00-3e1a-11eb-8788-77e8c2f38b84.png)

This is a file of the subprocess [output.txt](https://github.com/morrolinux/simple-ehm/files/5689095/output.txt)

**Comment by morrolinux** [comment]
For how long did you see it stuck before giving up?

**Comment by RCapolungo** [comment]
Almost half an hour

**Comment by morrolinux** [comment]
Yeah, try to let it go for 1 hour or so just to be sure it's not an ffmpeg (slow) seek issue.
Also try with a different video file and see if anything changes

**Comment by RCapolungo** [comment]
Ok, so i let it go for 2 h 45 min and nothing happend, the last ffmpeg process was stuck at 0% of CPU usage for the whole time.
I tried on multiple files and i noticed that if they last less than 10 minutes the last ffmepg process ends. 
i'm not sure what is the duration limit before the process stops working but for sure 1 h files get stuck

**Comment by morrolinux** [comment]
That's odd... But now that I think about it, you probably should remove
shell output piping from the merge command which is on another line

Il mar 15 dic 2020, 15:27 RCapolungo <notifications@github.com> ha scritto:

**Comment by RCapolungo** [comment]
Yes, the problem was the `stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE` in this lines.
https://github.com/morrolinux/simple-ehm/blob/11e90f9eb25f03209ef9db077da7bf708439666a/simple_ehm-runnable.py#L82
https://github.com/morrolinux/simple-ehm/blob/11e90f9eb25f03209ef9db077da7bf708439666a/simple_ehm-runnable.py#L243
https://github.com/morrolinux/simple-ehm/blob/11e90f9eb25f03209ef9db077da7bf708439666a/simple_ehm-runnable.py#L266

 i've just removed them and now it's working perfectly
 
Thanks for your help
