### ISSUE TITLE
Loading Error 

### ISSUE THREAD

**Issue by boringthing** [morrolinux/simple-ehm#9]
Hi, when I try to load the model with this line:
  model = tf.keras.models.load_model('model')
it gives me:
  KeyError: 'sample_weight_mode'

Can you help me? Thanks.

**Comment by morrolinux** [comment]
You need to give me some context here.
Are you talking about the notebook?
If so, which name did you give to the model? Have you run all the notebook
fine until that point? Which os are you running?

Il ven 15 gen 2021, 20:12 boringthing <notifications@github.com> ha scritto:

**Comment by boringthing** [comment]
Yes, I'm talking about "simple_ehm-runnable.py".

I didn't change the name of the model, so it's called "saved_model.pb" and it's located in the directory "model".

I tried to load the saved model actually because i wasn't able to run the notebook, the problem is that the directories containing datasets are empty. I'm using Win10.

Thanks.
(sorry i am a novice)

**Comment by morrolinux** [comment]
Then it's not the notebook.
I need to see the full shell output, including invocation parameters

Il sab 16 gen 2021, 12:47 boringthing <notifications@github.com> ha scritto:

**Comment by boringthing** [comment]
Sorry I meant "simple_ehm.ipynb", the notebook and not  "simple_ehm-runnable.py" as I wrote.

-Cambio lingua che ho la shell in italiano- (lol)

Ho provato pure a runnare dalla shell:
   ./simple_emh-runnable.py Desktop\Sistemi Complessi\Neuroscienze\lezione1
ma mi dice:
  ./simple_emh-runnable.py : Termine './simple_emh-runnable.py' non riconosciuto come nome di cmdlet, funzione,
  programma eseguibile o file script. Controllare l'ortografia del nome o verificare che il percorso sia incluso e
  corretto, quindi riprovare.
  In riga:1 car:1
  + ./simple_emh-runnable.py Desktop\Sistemi Complessi\Neuroscienze\lezio ...
  + ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (./simple_emh-runnable.py:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

e siccome non sono familiare con la shell di windows (di solito uso linux) ho lasciato perdere.

**Comment by morrolinux** [comment]
Mi sembra di aver capito che su Windows devi fare "python.exe
simple_ehm-runnable.py"
Altrimenti non vedo perché non provare ad eseguirlo su Linux ;)

Il sab 16 gen 2021, 19:23 boringthing <notifications@github.com> ha scritto:
